/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubes_pbo;

import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class Edit extends javax.swing.JFrame {

    /**
     * Creates new form Input
     */
    private String nama;
    private String id_pengguna;
    private int id_mutasi;
    
    public Edit(int idm,String idp, String nm) {
        nama=nm;
        id_pengguna=idp;
        id_mutasi=idm;
        initComponents();
    }
    private void kosong(){
//        IDMutasi.setText(null);
//        jumlah.setText(null);
//        tgl.setText(null);
//        keterangan.setSelectedItem(this);
//        jenis.setText(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jenisMutasi = new javax.swing.ButtonGroup();
        judul = new javax.swing.JLabel();
        jml_lbl = new javax.swing.JLabel();
        jumlah = new javax.swing.JTextField();
        tgl_lbl = new javax.swing.JLabel();
        tgl = new javax.swing.JFormattedTextField();
        keterangan_lbl = new javax.swing.JLabel();
        keterangan = new javax.swing.JComboBox<>();
        input = new javax.swing.JButton();
        jns_lbl = new javax.swing.JLabel();
        history = new javax.swing.JButton();
        contoh = new javax.swing.JLabel();
        pemasukan = new javax.swing.JRadioButton();
        pengeluaran = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kelompok 8");

        judul.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        judul.setText("EDIT");

        jml_lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jml_lbl.setText("Jumlah       :");

        tgl_lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tgl_lbl.setText("Tanggal      :");

        tgl.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy/MM/dd"))));

        keterangan_lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        keterangan_lbl.setText("Keterangan  :");

        keterangan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        keterangan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan & Minuman", "Mendesak", "Hiburan", "Amal", "Sandang", "Traveling", "Lain-lain..." }));

        input.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        input.setText("Input");
        input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputActionPerformed(evt);
            }
        });

        jns_lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jns_lbl.setText("Jenis           :");

        history.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        history.setText("History");
        history.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyActionPerformed(evt);
            }
        });

        contoh.setForeground(new java.awt.Color(102, 102, 102));
        contoh.setText("contoh : 2019-05-31");

        jenisMutasi.add(pemasukan);
        pemasukan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pemasukan.setText("Pemasukan");
        pemasukan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pemasukanActionPerformed(evt);
            }
        });

        jenisMutasi.add(pengeluaran);
        pengeluaran.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pengeluaran.setText("Pengeluaran");
        pengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pengeluaranActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(judul)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tgl_lbl)
                        .addGap(18, 18, 18)
                        .addComponent(tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(contoh)
                        .addContainerGap(52, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jns_lbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(pemasukan)
                                        .addGap(18, 18, 18)
                                        .addComponent(pengeluaran))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(keterangan_lbl)
                                            .addGap(19, 19, 19)
                                            .addComponent(keterangan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jml_lbl)
                                            .addGap(20, 20, 20)
                                            .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(6, 6, 6))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(history)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(judul)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tgl_lbl)
                    .addComponent(tgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contoh))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jml_lbl)
                    .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jns_lbl)
                    .addComponent(pemasukan)
                    .addComponent(pengeluaran))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(keterangan_lbl)
                    .addComponent(keterangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(126, 126, 126)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(history, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(192, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputActionPerformed
        try{
            String sql = "INSERT INTO mutasi VALUES ('"+id_mutasi+"','"+jumlah.getText()+"','"+tgl.getText()+"','"+keterangan.getSelectedItem()+"','"+jenisMutasi.getSelection().getActionCommand()+"')";
            java.sql.Connection conn=(Connection)tubes_pbo.main.koneksi();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_inputActionPerformed

    private void historyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyActionPerformed
        History his = new History(id_mutasi,id_pengguna,nama);
        his.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_historyActionPerformed

    private void pemasukanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pemasukanActionPerformed
        // TODO add your handling code here:
        pemasukan.setActionCommand("pemasukan");
    }//GEN-LAST:event_pemasukanActionPerformed

    private void pengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pengeluaranActionPerformed
        // TODO add your handling code here:
        pemasukan.setActionCommand("pengeluaran");
    }//GEN-LAST:event_pengeluaranActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Edit().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contoh;
    private javax.swing.JButton history;
    private javax.swing.JButton input;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.ButtonGroup jenisMutasi;
    private javax.swing.JLabel jml_lbl;
    private javax.swing.JLabel jns_lbl;
    private javax.swing.JLabel judul;
    private javax.swing.JTextField jumlah;
    private javax.swing.JComboBox<String> keterangan;
    private javax.swing.JLabel keterangan_lbl;
    private javax.swing.JRadioButton pemasukan;
    private javax.swing.JRadioButton pengeluaran;
    private javax.swing.JFormattedTextField tgl;
    private javax.swing.JLabel tgl_lbl;
    // End of variables declaration//GEN-END:variables
}
