/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubes_pbo;

/**
 *
 * @author Praktikan
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    private String nama;
    private String id_pengguna;
    private int id_mutasi;
    main x=new main();
    
    public Home(int idm,String idp, String nm) {
        nama=nm;
        id_pengguna=idp;
        id_mutasi=idm;
        initComponents();
        
        x.tampilHome2(id_mutasi,id_pengguna,nama);
    }
    
     public Home(int idm,String idp, String nm, int a) {
         nama=nm;
        id_pengguna=idp;
        id_mutasi=idm;
        initComponents();
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("checked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        username = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        balance_lbl = new javax.swing.JLabel();
        pemasukan_lbl = new javax.swing.JLabel();
        pengeluaran_lbl = new javax.swing.JLabel();
        histori = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        balance = new javax.swing.JLabel();
        pengeluaran = new javax.swing.JLabel();
        pemasukan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kelompok 8");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(460, 640));

        username.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username.setText("Username");

        logout.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        logout.setText("Log Out");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        balance_lbl.setBackground(new java.awt.Color(255, 255, 153));
        balance_lbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        balance_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        balance_lbl.setText("Balance (Rp.)");

        pemasukan_lbl.setBackground(new java.awt.Color(153, 255, 153));
        pemasukan_lbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pemasukan_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pemasukan_lbl.setText("Pemasukan (Rp.)");

        pengeluaran_lbl.setBackground(new java.awt.Color(255, 101, 101));
        pengeluaran_lbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pengeluaran_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pengeluaran_lbl.setText("Pengeluaran (Rp.)");

        histori.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        histori.setText("Riwayat");
        histori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historiActionPerformed(evt);
            }
        });

        tambah.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tambah.setText("Tambah Mutasi");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        balance.setBackground(new java.awt.Color(204, 204, 204));
        balance.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        balance.setForeground(new java.awt.Color(0, 0, 153));
        balance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        pengeluaran.setBackground(new java.awt.Color(204, 204, 204));
        pengeluaran.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        pengeluaran.setForeground(new java.awt.Color(255, 51, 51));
        pengeluaran.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        pemasukan.setBackground(new java.awt.Color(204, 204, 204));
        pemasukan.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        pemasukan.setForeground(new java.awt.Color(0, 153, 51));
        pemasukan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logout)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(balance_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pemasukan_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pengeluaran_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(histori, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tambah))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(balance, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pemasukan, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username)
                    .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(balance_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pemasukan_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pengeluaran_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pemasukan, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(balance, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(152, 152, 152)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(histori, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(204, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        new halaman1().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_logoutActionPerformed

    private void historiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historiActionPerformed
        new History(id_mutasi,id_pengguna,nama).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_historiActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        new Input(id_mutasi,id_pengguna,nama).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_tambahActionPerformed

    public void setKeterangan(String nama, double b, double m, double k){
        username.setText(nama);
        balance.setText(String.valueOf(b));
        pemasukan.setText(String.valueOf(m));
        pengeluaran.setText(String.valueOf(k));
    }
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Home().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel balance;
    private javax.swing.JLabel balance_lbl;
    private javax.swing.JButton histori;
    private javax.swing.JButton logout;
    private javax.swing.JLabel pemasukan;
    private javax.swing.JLabel pemasukan_lbl;
    private javax.swing.JLabel pengeluaran;
    private javax.swing.JLabel pengeluaran_lbl;
    private javax.swing.JButton tambah;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
