/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubes_pbo;

import java.util.Arrays;

/**
 *
 * @author Praktikan
 */
public class Input extends javax.swing.JFrame {
    
        
    private String nama;
    private String id_pengguna;
    private int id_mutasi;
    main x=new main();
    
    public Input(int idm,String idp, String nm) {
        nama=nm;
        id_pengguna=idp;
        id_mutasi=idm;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        JenisMutasi = new javax.swing.ButtonGroup();
        tgl_lbl = new javax.swing.JLabel();
        tanggal = new javax.swing.JFormattedTextField();
        contoh = new javax.swing.JLabel();
        jml_lbl = new javax.swing.JLabel();
        jumlah = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        pemasukan_rb = new javax.swing.JRadioButton();
        pengeluaran_rb = new javax.swing.JRadioButton();
        keterangan_lbl = new javax.swing.JLabel();
        keterangan = new javax.swing.JComboBox();
        input = new javax.swing.JButton();
        judul = new javax.swing.JLabel();
        Kembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kelompok 8");

        tgl_lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tgl_lbl.setText("Tanggal        :");

        tanggal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        tanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggalActionPerformed(evt);
            }
        });

        contoh.setForeground(new java.awt.Color(102, 102, 102));
        contoh.setText("contoh : 2019-05-31");

        jml_lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jml_lbl.setText("Jumlah         :");

        jumlah.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Jenis mutasi :");

        JenisMutasi.add(pemasukan_rb);
        pemasukan_rb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pemasukan_rb.setText("Pemasukan");
        pemasukan_rb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pemasukan_rbActionPerformed(evt);
            }
        });

        JenisMutasi.add(pengeluaran_rb);
        pengeluaran_rb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pengeluaran_rb.setText("Pengeluaran");
        pengeluaran_rb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pengeluaran_rbActionPerformed(evt);
            }
        });

        keterangan_lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        keterangan_lbl.setText("Keterangan  :");

        keterangan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        keterangan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Makan & Minum", "Mendesak", "Hiburan", "Amal" , "Sandang", "Traveling", "Lain-lain..."}));
        keterangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keteranganActionPerformed(evt);
            }
        });

        input.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        input.setText("Input");
        input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputActionPerformed(evt);
            }
        });

        judul.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        judul.setText("Tambah Mutasi");

        Kembali.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Kembali.setText("Kembali");
        Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Kembali)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(keterangan_lbl)
                                .addGap(18, 18, 18)
                                .addComponent(keterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jml_lbl)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(pemasukan_rb)
                                        .addGap(18, 18, 18)
                                        .addComponent(pengeluaran_rb))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tgl_lbl)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(judul)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(contoh)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(judul)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tgl_lbl)
                    .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contoh))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jml_lbl)
                    .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pemasukan_rb)
                    .addComponent(jLabel2)
                    .addComponent(pengeluaran_rb))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keterangan_lbl)
                    .addComponent(keterangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(162, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggalActionPerformed

    private void pemasukan_rbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pemasukan_rbActionPerformed
        // TODO add your handling code here:
        pemasukan_rb.setActionCommand("pemasukan");
    }//GEN-LAST:event_pemasukan_rbActionPerformed

    private void keteranganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keteranganActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_keteranganActionPerformed

    private void KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembaliActionPerformed
        new Home(id_mutasi,id_pengguna,nama).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_KembaliActionPerformed

    private void inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputActionPerformed
        String tgl=tanggal.getText();
        String jml=jumlah.getText();
        String jns=JenisMutasi.getSelection().getActionCommand();
        String ket=keterangan.getSelectedItem().toString();
//        Object jns=JenisMutasi.getSelection().getSelectedObjects();
//        Object ket=keterangan.getSelectedItem();
        id_mutasi+=1;
        x.tambahMutasi(tgl,jml,jns,ket,id_mutasi);
        
        new Home(id_mutasi,id_pengguna,nama).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_inputActionPerformed

    private void pengeluaran_rbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pengeluaran_rbActionPerformed
        // TODO add your handling code here:
        pengeluaran_rb.setActionCommand("pengeluaran");
    }//GEN-LAST:event_pengeluaran_rbActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Input().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup JenisMutasi;
    private javax.swing.JButton Kembali;
    private javax.swing.JLabel contoh;
    private javax.swing.JButton input;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel jml_lbl;
    private javax.swing.JLabel judul;
    private javax.swing.JFormattedTextField jumlah;
    private javax.swing.JComboBox keterangan;
    private javax.swing.JLabel keterangan_lbl;
    private javax.swing.JRadioButton pemasukan_rb;
    private javax.swing.JRadioButton pengeluaran_rb;
    private javax.swing.JFormattedTextField tanggal;
    private javax.swing.JLabel tgl_lbl;
    // End of variables declaration//GEN-END:variables
}
